### ISSUE TITLE
Only the GM can roll

### ISSUE THREAD

**Issue by Hypnonymoose** [yithian/dlyg#1]
For some reason, only the GM can make rolls. I can see why that would be a thing, but it feels impractical to me. Maybe add a flag to turn that on and off?

On the same note, it appears as though my players can only see my rolls after they refresh, which is also very impractical, and also fairly easy to fix with some magic Javascript.

Other than that, it's awesome! Thank you for putting this out there.

**Comment by yithian** [comment]
it appears something terrible has happened to my openshift gear... i'll try to figure out what (or migrate data to a new gear) tomorrow

**Comment by yithian** [comment]
there we go. that should fix it. please let me know if anything is off!

glad you're enjoying the site :)
